const PDFDocument = require("pdfkit");
const DoctorVisitSummary = require("../models/DoctorVisitSummary");

exports.generateDoctorSummaryPDF = async (req, res) => {
  try {
    const { summaryId } = req.params;
    const userId = req.user.id;

    // 1️⃣ Fetch summary (ownership check)
    const summaryDoc = await DoctorVisitSummary.findOne({
      _id: summaryId,
      user: userId
    });

    if (!summaryDoc) {
      return res.status(404).json({
        message: "Doctor visit summary not found"
      });
    }

    const { summary, generatedAt } = summaryDoc;

    // 2️⃣ Create PDF
    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=doctor-visit-summary.pdf"
    );

    doc.pipe(res);

    // ======================
    // PDF CONTENT
    // ======================

    // Title
    doc.fontSize(20).text("Doctor Visit Summary", { align: "center" });
    doc.moveDown(1);

    doc
      .fontSize(10)
      .text(`Generated on: ${generatedAt.toDateString()}`, {
        align: "right"
      });

    doc.moveDown(2);

    // Reason for visit
    doc.fontSize(14).text("Reason for Visit", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).text(summary.reason_for_visit);
    doc.moveDown(1.5);

    // Key Risk Drivers
    doc.fontSize(14).text("Key Risk Drivers", { underline: true });
    doc.moveDown(0.5);
    summary.key_risk_drivers.forEach(item => {
      doc.fontSize(12).text(`• ${item}`);
    });
    doc.moveDown(1.5);

    // Relevant Trends
    doc.fontSize(14).text("Relevant Trends", { underline: true });
    doc.moveDown(0.5);
    summary.relevant_trends.forEach(item => {
      doc.fontSize(12).text(`• ${item}`);
    });
    doc.moveDown(1.5);

    // Suggested Evaluations
    doc.fontSize(14).text("Suggested Evaluations", { underline: true });
    doc.moveDown(0.5);
    summary.suggested_evaluations.forEach(item => {
      doc.fontSize(12).text(`• ${item}`);
    });

    doc.moveDown(2);

    // Disclaimer
    doc
      .fontSize(9)
      .fillColor("gray")
      .text(
        "Disclaimer: This summary is generated by an AI-assisted system to support clinical decision-making. It does not constitute a medical diagnosis or treatment recommendation.",
        {
          align: "left"
        }
      );

    doc.end();

  } catch (error) {
    res.status(500).json({
      message: "Failed to generate PDF"
    });
  }
};
